profile_name: "Default_v1"
description: "Standard baseline protection against PII (Regex) and Injection attacks. Perfect for general experimentation."
detectors:
  pii:
    enabled: true
    patterns: 
      - "EMAIL"
      - "PHONE"
      - "SSN"
      - "CREDIT_CARD"
  injection:
    enabled: true
    # Default keywords are used if list is empty/omitted
  secrets:
    enabled: true
    # Default patterns used
  topics:
    enabled: false
  semantic_blocking:
    enabled: true
    threshold: 0.45
    forbidden_intents:
      - "jailbreak attempt"
      - "prompt injection"
      - "revealing system instructions"
      - "bypassing safety filters"
